import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Product from './Product';
import Blog from './Blog'
import About from './About';
import Contact from './Contact';
import Event from './Event'
import Counter from './Counter';
import Navbar from '../components/Navbar';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>hellow this is main page</h1>
      <span className="link"><Link href="/About">About</Link></span>
      <span className="link"><Link href="/Contact">Contact</Link></span>
      <span className="link"><Link href="/Event">Event</Link></span>
      <span className="link"><Link href="/Product">Product</Link></span>
      <span className="link"><Link href="/Blog">Blog</Link></span>
      <Counter />
      <div className="card">
        <div className="card-body text-center">
          This is some text within a card body.

        </div>
      </div>

    </div>
  )
}
